Chat plugin, Null exceptions [12:05:11] [Async Chat Thread - #7/ERROR]: Could not pass event AsyncPlayerChatEvent to StaffChat v1.0 org.bukkit.event.EventException 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2] 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2] 	at net.minecraft.server.v1_8_R2.PlayerConnection.chat(PlayerConnection.java:1061) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2] 	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:999) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2] 	at net.minecraft.server.v1_8_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45] 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_45] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_45] 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45] Caused by: java.lang.NullPointerException 	at me.merinthium.com.listeners.ChatListener.onPlayerChat(ChatListener.java:23) ~[?:?] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45] 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2] 	... 11 more
[12:05:15] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing
command 'staffchat' in plugin StaffChat v1.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at
org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at
org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at
net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139)
[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at
net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974)
[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at
net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at
net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at
net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at
net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712)
[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at
net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at
net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at
net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]